#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App.Resource", IsApplication=true)]

namespace App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.fab.Resource.Attribute.fab_colorDisabled = global::App.Resource.Attribute.fab_colorDisabled;
			global::com.refractored.fab.Resource.Attribute.fab_colorNormal = global::App.Resource.Attribute.fab_colorNormal;
			global::com.refractored.fab.Resource.Attribute.fab_colorPressed = global::App.Resource.Attribute.fab_colorPressed;
			global::com.refractored.fab.Resource.Attribute.fab_colorRipple = global::App.Resource.Attribute.fab_colorRipple;
			global::com.refractored.fab.Resource.Attribute.fab_shadow = global::App.Resource.Attribute.fab_shadow;
			global::com.refractored.fab.Resource.Attribute.fab_size = global::App.Resource.Attribute.fab_size;
			global::com.refractored.fab.Resource.Color.fab_material_blue_500 = global::App.Resource.Color.fab_material_blue_500;
			global::com.refractored.fab.Resource.Dimension.fab_elevation_lollipop = global::App.Resource.Dimension.fab_elevation_lollipop;
			global::com.refractored.fab.Resource.Dimension.fab_scroll_threshold = global::App.Resource.Dimension.fab_scroll_threshold;
			global::com.refractored.fab.Resource.Dimension.fab_shadow_size = global::App.Resource.Dimension.fab_shadow_size;
			global::com.refractored.fab.Resource.Dimension.fab_size_mini = global::App.Resource.Dimension.fab_size_mini;
			global::com.refractored.fab.Resource.Dimension.fab_size_normal = global::App.Resource.Dimension.fab_size_normal;
			global::com.refractored.fab.Resource.Drawable.fab_shadow = global::App.Resource.Drawable.fab_shadow;
			global::com.refractored.fab.Resource.Drawable.fab_shadow_mini = global::App.Resource.Drawable.fab_shadow_mini;
			global::com.refractored.fab.Resource.Id.mini = global::App.Resource.Id.mini;
			global::com.refractored.fab.Resource.Id.normal = global::App.Resource.Id.normal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton = global::App.Resource.Styleable.FloatingActionButton;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::App.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::App.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::App.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::App.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::App.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_size = global::App.Resource.Styleable.FloatingActionButton_fab_size;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int fab_colorDisabled = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int fab_colorNormal = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int fab_colorPressed = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fab_colorRipple = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fab_shadow = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fab_size = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int fab_material_blue_500 = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050004
			public const int fab_elevation_lollipop = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int fab_scroll_threshold = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int fab_shadow_size = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int fab_size_mini = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int fab_size_normal = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fab_shadow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fab_shadow_mini = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int btnAdd = 2131165189;
			
			// aapt resource value: 0x7f070010
			public const int button1 = 2131165200;
			
			// aapt resource value: 0x7f070006
			public const int detailView = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int edtCellphone = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int edtEmail = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int edtName = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int img_user = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int linearLayout1 = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int mini = 2131165184;
			
			// aapt resource value: 0x7f070012
			public const int myListView = 2131165202;
			
			// aapt resource value: 0x7f07000a
			public const int myListViewAdapter = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int normal = 2131165185;
			
			// aapt resource value: 0x7f07000f
			public const int searchView1 = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int textView1 = 2131165201;
			
			// aapt resource value: 0x7f07000d
			public const int txt_email = 2131165197;
			
			// aapt resource value: 0x7f070008
			public const int txt_user_email = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int txt_user_name = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int txt_user_phone = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int txt_username = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int addContact = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Details = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListViewAdapter = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatingActionButton = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
