#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App.Resource", IsApplication=true)]

namespace App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.fab.Resource.Attribute.fab_colorDisabled = global::App.Resource.Attribute.fab_colorDisabled;
			global::com.refractored.fab.Resource.Attribute.fab_colorNormal = global::App.Resource.Attribute.fab_colorNormal;
			global::com.refractored.fab.Resource.Attribute.fab_colorPressed = global::App.Resource.Attribute.fab_colorPressed;
			global::com.refractored.fab.Resource.Attribute.fab_colorRipple = global::App.Resource.Attribute.fab_colorRipple;
			global::com.refractored.fab.Resource.Attribute.fab_shadow = global::App.Resource.Attribute.fab_shadow;
			global::com.refractored.fab.Resource.Attribute.fab_size = global::App.Resource.Attribute.fab_size;
			global::com.refractored.fab.Resource.Attribute.layoutManager = global::App.Resource.Attribute.layoutManager;
			global::com.refractored.fab.Resource.Attribute.reverseLayout = global::App.Resource.Attribute.reverseLayout;
			global::com.refractored.fab.Resource.Attribute.spanCount = global::App.Resource.Attribute.spanCount;
			global::com.refractored.fab.Resource.Attribute.stackFromEnd = global::App.Resource.Attribute.stackFromEnd;
			global::com.refractored.fab.Resource.Color.fab_material_blue_500 = global::App.Resource.Color.fab_material_blue_500;
			global::com.refractored.fab.Resource.Dimension.fab_elevation_lollipop = global::App.Resource.Dimension.fab_elevation_lollipop;
			global::com.refractored.fab.Resource.Dimension.fab_scroll_threshold = global::App.Resource.Dimension.fab_scroll_threshold;
			global::com.refractored.fab.Resource.Dimension.fab_shadow_size = global::App.Resource.Dimension.fab_shadow_size;
			global::com.refractored.fab.Resource.Dimension.fab_size_mini = global::App.Resource.Dimension.fab_size_mini;
			global::com.refractored.fab.Resource.Dimension.fab_size_normal = global::App.Resource.Dimension.fab_size_normal;
			global::com.refractored.fab.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::App.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::com.refractored.fab.Resource.Drawable.fab_shadow = global::App.Resource.Drawable.fab_shadow;
			global::com.refractored.fab.Resource.Drawable.fab_shadow_mini = global::App.Resource.Drawable.fab_shadow_mini;
			global::com.refractored.fab.Resource.Id.item_touch_helper_previous_elevation = global::App.Resource.Id.item_touch_helper_previous_elevation;
			global::com.refractored.fab.Resource.Id.mini = global::App.Resource.Id.mini;
			global::com.refractored.fab.Resource.Id.normal = global::App.Resource.Id.normal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton = global::App.Resource.Styleable.FloatingActionButton;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::App.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::App.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::App.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::App.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::App.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_size = global::App.Resource.Styleable.FloatingActionButton_fab_size;
			global::com.refractored.fab.Resource.Styleable.RecyclerView = global::App.Resource.Styleable.RecyclerView;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_android_orientation = global::App.Resource.Styleable.RecyclerView_android_orientation;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_layoutManager = global::App.Resource.Styleable.RecyclerView_layoutManager;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_reverseLayout = global::App.Resource.Styleable.RecyclerView_reverseLayout;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_spanCount = global::App.Resource.Styleable.RecyclerView_spanCount;
			global::com.refractored.fab.Resource.Styleable.RecyclerView_stackFromEnd = global::App.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int fab_colorDisabled = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int fab_colorNormal = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int fab_colorPressed = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int fab_colorRipple = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fab_shadow = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int fab_size = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int fab_material_blue_500 = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040005
			public const int fab_elevation_lollipop = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int fab_scroll_threshold = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int fab_shadow_size = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int fab_size_mini = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int fab_size_normal = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fab_shadow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int fab_shadow_mini = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int btnAdd = 2131034118;
			
			// aapt resource value: 0x7f050011
			public const int button1 = 2131034129;
			
			// aapt resource value: 0x7f050007
			public const int detailView = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int edtCellphone = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int edtEmail = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int edtName = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int img_user = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int linearLayout1 = 2131034127;
			
			// aapt resource value: 0x7f050001
			public const int mini = 2131034113;
			
			// aapt resource value: 0x7f050013
			public const int myListView = 2131034131;
			
			// aapt resource value: 0x7f05000b
			public const int myListViewAdapter = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int normal = 2131034114;
			
			// aapt resource value: 0x7f050010
			public const int searchView1 = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int textView1 = 2131034130;
			
			// aapt resource value: 0x7f05000e
			public const int txt_email = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int txt_user_email = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int txt_user_name = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int txt_user_phone = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int txt_username = 2131034125;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int addContact = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Details = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListViewAdapter = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatingActionButton = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
